# Generated by Django 5.2.5 on 2025-08-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('image', models.URLField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('equipment', models.CharField(blank=True, max_length=255, null=True)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('fuel', models.CharField(blank=True, max_length=64, null=True)),
                ('km', models.CharField(blank=True, max_length=10, null=True)),
                ('color', models.CharField(blank=True, max_length=64, null=True)),
                ('body', models.CharField(blank=True, max_length=64, null=True)),
                ('transmission', models.CharField(blank=True, max_length=64, null=True)),
                ('mileage', models.IntegerField(blank=True, null=True)),
                ('capacity', models.CharField(blank=True, max_length=10, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offers',
                'ordering': ['-date'],
            },
        ),
    ]
