# Generated by Django 5.2.5 on 2025-08-06 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='km',
            new_name='hp',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='url',
            new_name='path',
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_id',
            field=models.CharField(default='a', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
