# Generated by Django 5.2.5 on 2025-08-07 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_rename_km_offer_hp_rename_url_offer_path_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferFailed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.URLField(max_length=255, unique=True)),
                ('error_message', models.TextField()),
            ],
            options={
                'verbose_name': 'Failed Offer',
                'verbose_name_plural': 'Failed Offers',
                'ordering': ['path'],
            },
        ),
    ]
